service: serverless
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          
  goodbye:
    handler: handler.goodbye
    events:
      - http:
          path: /goodbye
          method: get
