# Use the official MySQL image version 8.0.22 as the base image
FROM mysql:8.0.22

# Set the password for the root user
ENV MYSQL_ROOT_PASSWORD kETeRmAtinSaCis.

# Create a database named 'db_eam' when the container starts
ENV MYSQL_DATABASE db_eam

# Configure the MySQL user (in this case, root) and its password
ENV MYSQL_USER root
ENV MYSQL_PASSWORD kETeRmAtinSaCis.

# Expose port 3306 to allow external connections to MySQL
EXPOSE 3306